### ISSUE TITLE
Voltage warning should be placed on RC controller page

### ISSUE THREAD

**Issue by fengye** [autorope/donkeydocs#11]
I just found [RC transmitter can be used as an input source](https://docs.donkeycar.com/parts/rc.html). However, from my experience not all RC receiver send 3.3v PWM signals. An exmaple is Tamiya's [TRU-08 ](https://www.tamiyausa.com/shop/electronics/finespec-24ghz-radio-system/) which gives out 6V, so in this case you'll need voltage shifters. Some other receiver does output 3.3v but that needs to be warned in the document, as this can permanently damage the Pi or Nano which GPIOs are only tolerant to 3.3v.

**Comment by DocGarbanzo** [comment]
@fengye - Thanks for raising this issue. You are right, the PWM output of the RC receiver is equal to the input voltage. Our documentation seems to correctly state to run the RC receiver off the 3.3V rail of the RPi - https://docs.donkeycar.com/parts/rc/. Do you think this requires an extra warning on that page?

**Comment by fengye** [comment]
I must have skipped that part. However, I assume people from a background of RC community might think the receiver should get its power directly from an ESC unit by default, so here I think it won't hurt to emphasis it and warn the user of the need to strictly connect the receiver to the 3.3V power rail from Pi GPIO, or otherwise expect some hardware failure.

**Comment by DocGarbanzo** [comment]
I have added a warning to the page to highlight the danger. Thanks for pointing this out.
